
veeams: 
  - host: host.domaine
    port: 9398
    user: 'user'
    password: 'password'
#      protocol: https
    verify_ssl: false
    timeout: 20
#    keep_session: true # default
#    default_labels:
#      - name: veeam_em
#        value: my_veeam_em_server.domain
#    proxy:
#      url: http://my.proxy.domain:port/
#      protocol: https

weblisten:
  address: 0.0.0.0
  port: 9247

logger:
  level: info
  facility: syslog

metrics_file: "conf/metrics/*_metrics.yml"

